### ISSUE TITLE
Ошибка в описании

### ISSUE THREAD

**Issue by x09** [altlinux/admx-basealt#47]
![изображение](https://user-images.githubusercontent.com/1303927/151115877-5c342234-4711-41b2-aaf4-c49cc0f7edaa.png)

Писать имена пакетов надо не через пробел, а по одному в строку. 

Иначе будем иметь вот это
![изображение](https://user-images.githubusercontent.com/1303927/151116161-0a51ca62-df67-4719-92a5-52d6d6f99b4a.png)

**Comment by mastersin** [comment]
В новом релизе эта опция переименована и сделана через список.
