### ISSUE TITLE
GSettings

### ISSUE THREAD

**Issue by ekorneechev** [altlinux/admx-basealt#8]
Просьба добавить шаблоны для GSettings, минимально бы хотелось:

- настройка фонового изображения (схема _org.mate.background_)
- настройка хранителя экрана (схема _org.mate.screensaver_)
- настройка удаленного доступа по VNC (схема _org.gnome.Vino_ из пакета _vino-mate_)

**Comment by NIR-Ginko** [comment]
We'll implement this but I can't tell you the terms at the moment.

**Comment by NIR-Ginko** [comment]
At the moment the most interesting mappings (the ones you've asked for) are implemented for RSAT parameters so it is not obvious if we should implements GSettings in ADMX.

**Comment by mastersin** [comment]
Все предложенные политики добавлены, готовится новый релиз.
